version: '2.4'
services:

  websocket_cli:
    container_name: websocket_client
    build: ./docker/nginx
      #context: ./docker/nginx
      #dockerfile: Dockerfile
      #args:
      #  - WWW_DOMAIN_NAME=www.chatties.shop
    ports:
      - "80:80"
      - "443:443"
    working_dir: /etc/nginx
    volumes:
      - ./template:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always

  # websocket app
  websocket_svr:
    container_name: websocket_server
    build: ./docker/python
    ports:
      - 8888:8888
    volumes:
      # host의 경로를 컨테이너 내부와 마운트
      - .:/websocket_server
      - /etc/letsencrypt:/etc/letsencrypt
    working_dir: /websocket_server
    restart: always

  web_svr:
    container_name: web_server
    build: ./docker/python-web
    ports:
      - 8889:8889
    volumes:
      # host의 경로를 컨테이너 내부와 마운트
      - .:/websocket_server
      - /etc/letsencrypt:/etc/letsencrypt
    working_dir: /websocket_server
    restart: always